version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    cooldown:
      default-days: 7

    groups:
      production:
        patterns:
          - "amplfi"
          - "ml4gw"
          - "jsonargparse"
          - "h5py"
          - "numpy"
          - "matplotlib"
          - "gwpy"
          - "ligo-skymap"
          - "huggingface_hub"

      documentation:
        patterns:
          - "sphinx*"
          - "myst*"
          - "linkify-it-py"
          
      development:
        patterns: ["*"]
        exclude-patterns:
          - "amplfi"
          - "ml4gw"
          - "jsonargparse"
          - "h5py"
          - "numpy"
          - "matplotlib"
          - "gwpy"
          - "ligo-skymap"
          - "huggingface_hub"
          - "sphinx*"
          - "myst*"
          - "linkify-it-py"

    versioning-strategy: increase-if-necessary

  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    groups:
      conda-deps:
        patterns:
          - "*"
